// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCttAWp3Wu82Y9RHkbrGBOIonMCS1FSc6E',
    appId: '1:1040516778610:web:648862eeec9a226c02d0eb',
    messagingSenderId: '1040516778610',
    projectId: 'secwrite-app',
    authDomain: 'secwrite-app.firebaseapp.com',
    storageBucket: 'secwrite-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbVVTZqtIkCgLEcYkYGjU75wSI2Yt3wlU',
    appId: '1:1040516778610:android:fe764adf6523c29802d0eb',
    messagingSenderId: '1040516778610',
    projectId: 'secwrite-app',
    storageBucket: 'secwrite-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPQA6GxDYy5UlVHxGMh_7AxlcnpQIBdpY',
    appId: '1:1040516778610:ios:46ff2f88f0181fce02d0eb',
    messagingSenderId: '1040516778610',
    projectId: 'secwrite-app',
    storageBucket: 'secwrite-app.appspot.com',
    iosBundleId: 'com.example.secwriteapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPQA6GxDYy5UlVHxGMh_7AxlcnpQIBdpY',
    appId: '1:1040516778610:ios:b22b13a301f6072a02d0eb',
    messagingSenderId: '1040516778610',
    projectId: 'secwrite-app',
    storageBucket: 'secwrite-app.appspot.com',
    iosBundleId: 'com.example.secwriteapp.RunnerTests',
  );
}
